### ISSUE TITLE
ESLint throws issues when using "called"

### ISSUE THREAD

**Issue by abitwise** [domenic/sinon-chai#90] opened 2017-03-29 12:45 UTC
- ESLint will throw issue for following sentence:
`expect(stub).to.have.been.called;`
1 issue found:
... Expected an assignment or function call and instead saw an expression. (no-unused-expressions)

- ESLint would not throw "no-unused-expressions" for this code:
`expect(stub).to.have.been.called();`
But it does not work as .called is not function: TypeError: expect(...).to.have.been.called is not a function

**Comment by domenic** [comment] 2017-03-29 12:57
Dupe of https://github.com/domenic/sinon-chai/issues/20

**Closed by domenic** 2017-03-29 12:57 UTC
